name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Configurar Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26"
      
      # TODO: adicionar um passo para compilar a aplicacao Go.
      # Dica: use apenas um comando.

      # TODO: adicionar um passo para executar os testes.
      # Dica: use apenas um comando.
