name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Configurar Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26"
      
      - name: Compilar a aplicacao Go
        run: go build -v ./...

      - name: Executar os testes
        run: go test -v ./...